import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {WebSocketServer} from 'ws';
import {config} from '../config.js';import {db,setting,setSetting,now} from '../database/index.js';import {browse,scan,allowedRoots,safePath} from '../filesystem/index.js';import {GoogleDriveProvider,connectedAccount} from '../providers/google-drive/index.js';import {preflight,createJob,listJobs,jobDetail,jobAction} from '../core/jobs.js';import {queueSummary} from '../core/queue.js';import {pauseClaims,resumeClaims} from '../core/workers.js';import {snapshot,health,doctor} from '../core/system.js';import {events,emit} from '../events.js';import {Events} from '../contracts.js';import {log} from '../logger.js';import {reconcileRemote} from '../core/reconcile.js';

const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon','.json':'application/json'};
function send(res,status,data,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(JSON.stringify(status>=400?{ok:false,error:{code:data.code||'ERROR',message:data.message||String(data),details:data.details}}:{ok:true,data}));}
async function body(req){let n=0,chunks=[];for await(const c of req){n+=c.length;if(n>1024*1024)throw Object.assign(new Error('Request body too large'),{status:413});chunks.push(c);}if(!n)return {};try{return JSON.parse(Buffer.concat(chunks));}catch{throw Object.assign(new Error('Invalid JSON'),{status:400,code:'VALIDATION_ERROR'});}}
const route=(method,pattern,handler)=>({method,pattern,handler});
const routes=[];
routes.push(route('GET','/api/v1/setup/status',()=>({complete:setting('onboarding_complete',false),roots:allowedRoots(),oauthConfigured:!!db().prepare(`SELECT 1 FROM oauth_credentials WHERE provider='google'`).get(),account:connectedAccount(),lastScan:setting('last_scan',null)})));
routes.push(route('POST','/api/v1/setup/config',async({req})=>{const b=await body(req);if(b.storageRoots){for(const p of b.storageRoots)safePath(p);setSetting('storage_roots',b.storageRoots);}if(b.workerCount!=null){const n=Number(b.workerCount);if(!Number.isInteger(n)||n<1||n>10)throw new Error('Worker count must be 1-10');setSetting('worker_count',n);}return {saved:true};}));
routes.push(route('POST','/api/v1/setup/complete',async()=>{if(!connectedAccount())throw Object.assign(new Error('Connect Google Drive first'),{code:'AUTH_REQUIRED'});if(!setting('last_scan'))throw Object.assign(new Error('Complete the initial device scan first'),{code:'SETUP_INCOMPLETE'});setSetting('onboarding_complete',true);return {complete:true};}));
routes.push(route('GET','/api/v1/system/snapshot',snapshot));routes.push(route('GET','/api/v1/system/health',health));routes.push(route('GET','/api/v1/system/doctor',doctor));
routes.push(route('GET','/api/v1/accounts',()=>db().prepare('SELECT id,provider,email,display_name name,status,created_at,updated_at FROM accounts ORDER BY updated_at DESC').all()));
routes.push(route('POST','/api/v1/accounts/google/credentials',async({req})=>{const b=await body(req);return new GoogleDriveProvider().saveCredentials(b);}));
routes.push(route('POST','/api/v1/accounts/google/connect',async()=>{const state=crypto.randomBytes(24).toString('hex');setSetting('oauth_state',{value:state,expires:Date.now()+10*60_000});return {url:new GoogleDriveProvider().authUrl(state)};}));
routes.push(route('GET','/api/v1/accounts/google/callback',async({url,res})=>{const expected=setting('oauth_state'),code=url.searchParams.get('code'),state=url.searchParams.get('state');if(!expected||state!==expected.value||expected.expires<Date.now())throw Object.assign(new Error('OAuth state is invalid or expired'),{status:400});const a=await new GoogleDriveProvider().exchange(code);setSetting('oauth_state',null);emit(Events.DRIVE_CONNECTED,a);res.writeHead(302,{location:'/?oauth=connected'});res.end();return Symbol.for('sent');}));
routes.push(route('POST','/api/v1/accounts/:id/disconnect',({params})=>{new GoogleDriveProvider(Number(params.id)).disconnect();emit(Events.DRIVE_DISCONNECTED,{id:Number(params.id)});return {disconnected:true};}));
routes.push(route('GET','/api/v1/storage',async()=> (await snapshot()).storage));
routes.push(route('GET','/api/v1/local/browse',async({url})=>{const out=await browse(url.searchParams.get('path'));const a=connectedAccount();if(a){const q=db().prepare(`SELECT l.canonical_path,m.verification_status,m.uploaded_fingerprint,l.fingerprint FROM local_files l LEFT JOIN file_mappings m ON m.local_file_id=l.id AND m.account_id=? WHERE l.canonical_path=?`);out.items=out.items.map(x=>{const r=q.get(a.id,x.path);return {...x,status:!r?'NOT_UPLOADED':r.verification_status==='MISSING_REMOTE'?'MISSING_REMOTE':r.uploaded_fingerprint===r.fingerprint?'UPLOADED':'CHANGED'};});}return out;}));
routes.push(route('POST','/api/v1/local/scan',async({req})=>{const b=await body(req);setImmediate(()=>scan(b.path).catch(e=>log('ERROR','scan failed',{message:e.message})));return {started:true,path:safePath(b.path)};}));
routes.push(route('GET','/api/v1/drive/files',async({url})=>{const a=connectedAccount();if(!a)throw Object.assign(new Error('Google account not connected'),{code:'AUTH_REQUIRED'});return new GoogleDriveProvider(a.id).listFiles({parentId:url.searchParams.get('parentId')||'root',query:url.searchParams.get('query')||'',pageToken:url.searchParams.get('pageToken')||''});}));
routes.push(route('POST','/api/v1/drive/reconcile',()=>reconcileRemote(100)));
routes.push(route('POST','/api/v1/drive/folders',async({req})=>{const b=await body(req),a=connectedAccount();if(!a)throw Object.assign(new Error('Google account not connected'),{code:'AUTH_REQUIRED'});if(!b.name||/[\\/\0]/.test(b.name))throw new Error('Invalid folder name');return new GoogleDriveProvider(a.id).createFolder(b.name,b.parentId||'root');}));
routes.push(route('POST','/api/v1/jobs/preflight',async({req})=>preflight(await body(req))));
routes.push(route('POST','/api/v1/jobs',async({req})=>createJob(await body(req),req.headers['idempotency-key'])));
routes.push(route('GET','/api/v1/jobs',({url})=>listJobs(url.searchParams.get('limit'))));routes.push(route('GET','/api/v1/jobs/:id',({params})=>{const x=jobDetail(params.id);if(!x)throw Object.assign(new Error('Job not found'),{code:'NOT_FOUND',status:404});return x;}));
for(const action of ['pause','resume','retry','cancel'])routes.push(route('POST',`/api/v1/jobs/:id/${action}`,({params})=>jobAction(params.id,action)));
routes.push(route('GET','/api/v1/queue',queueSummary));routes.push(route('POST','/api/v1/queue/pause',()=>{pauseClaims();db().prepare(`UPDATE jobs SET state='PAUSED',updated_at=? WHERE state IN ('QUEUED','RUNNING','WAITING_NETWORK')`).run(now());db().prepare(`UPDATE job_files SET state='PAUSED',updated_at=? WHERE state IN ('QUEUED','RETRY_WAIT','WAITING_NETWORK')`).run(now());return {paused:true};}));routes.push(route('POST','/api/v1/queue/resume',()=>{db().prepare(`UPDATE jobs SET state='QUEUED',updated_at=? WHERE state='PAUSED'`).run(now());db().prepare(`UPDATE job_files SET state='QUEUED',updated_at=? WHERE state='PAUSED'`).run(now());resumeClaims();return {resumed:true};}));routes.push(route('POST','/api/v1/queue/retry-failed',()=>{const r=db().prepare(`UPDATE job_files SET state='QUEUED',retry_count=0,next_attempt_at=NULL,error_class=NULL,error_message=NULL,updated_at=? WHERE state='FAILED'`).run(now());return {retried:r.changes};}));routes.push(route('POST','/api/v1/queue/clear-completed',()=>{const r=db().prepare(`DELETE FROM jobs WHERE state='COMPLETED'`).run();return {cleared:r.changes};}));
routes.push(route('GET','/api/v1/history',()=>db().prepare('SELECT * FROM history ORDER BY created_at DESC LIMIT 200').all()));routes.push(route('GET','/api/v1/notifications',()=>db().prepare('SELECT * FROM notifications ORDER BY created_at DESC LIMIT 200').all()));routes.push(route('POST','/api/v1/notifications/:id/read',({params})=>{db().prepare('UPDATE notifications SET is_read=1 WHERE id=?').run(params.id);return {read:true};}));routes.push(route('DELETE','/api/v1/notifications/read',()=>{const r=db().prepare('DELETE FROM notifications WHERE is_read=1').run();return {cleared:r.changes};}));routes.push(route('GET','/api/v1/metrics',()=>db().prepare(`SELECT name,value,recorded_at FROM metrics WHERE recorded_at>=datetime('now','-1 hour') ORDER BY recorded_at LIMIT 1000`).all()));routes.push(route('GET','/api/v1/settings',()=>({workerCount:setting('worker_count',config.workers),maxRetries:setting('max_retries',config.maxRetries),chunkSize:setting('chunk_size',config.chunkSize),storageRoots:allowedRoots()})));routes.push(route('PATCH','/api/v1/settings',async({req})=>{const b=await body(req);if(b.workerCount!=null){if(!Number.isInteger(Number(b.workerCount))||Number(b.workerCount)<1||Number(b.workerCount)>10)throw new Error('workerCount must be 1-10');setSetting('worker_count',Number(b.workerCount));}if(b.maxRetries!=null)setSetting('max_retries',Math.max(0,Math.min(50,Number(b.maxRetries))));if(b.chunkSize!=null)setSetting('chunk_size',Math.max(262144,Math.min(67108864,Number(b.chunkSize))));return {saved:true,restartRequired:b.workerCount!=null};}));
function match(pattern,pathname){const a=pattern.split('/'),b=pathname.split('/');if(a.length!==b.length)return null;const p={};for(let i=0;i<a.length;i++){if(a[i].startsWith(':'))p[a[i].slice(1)]=decodeURIComponent(b[i]);else if(a[i]!==b[i])return null;}return p;}
async function handler(req,res){const host=req.headers.host||'',allowedHosts=new Set([`${config.host}:${config.port}`,`127.0.0.1:${config.port}`,`localhost:${config.port}`]);if(!allowedHosts.has(host))return send(res,403,{code:'INVALID_HOST',message:'Host is not allowed'});const origin=req.headers.origin;if(origin&&!new Set([...allowedHosts].map(x=>`http://${x}`)).has(origin))return send(res,403,{code:'INVALID_ORIGIN',message:'Origin is not allowed'});const url=new URL(req.url,`http://${host}`);if(url.pathname.startsWith('/api/')){const r=routes.find(x=>x.method===req.method&&match(x.pattern,url.pathname));if(!r)return send(res,404,{code:'NOT_FOUND',message:'Endpoint not found'});try{const result=await r.handler({req,res,url,params:match(r.pattern,url.pathname)});if(result!==Symbol.for('sent'))send(res,200,result);}catch(e){log('WARN','api error',{path:url.pathname,message:e.message});send(res,e.status||(['NOT_FOUND'].includes(e.code)?404:400),{code:e.code||'REQUEST_FAILED',message:e.message,details:e.details});}return;}let rel=url.pathname==='/'?'index.html':url.pathname.slice(1);rel=path.normalize(rel).replace(/^\.\.(\/|\\|$)/,'');const file=path.join(config.webDir,rel);if(!file.startsWith(config.webDir)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(302,{location:'/'});return res.end();}res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':rel==='index.html'?'no-cache':'public, max-age=3600'});fs.createReadStream(file).pipe(res);}
export function createServer(){const server=http.createServer(handler),wss=new WebSocketServer({server,path:'/ws'});wss.on('connection',ws=>{ws.send(JSON.stringify({event:'system.status',ts:now(),data:{connected:true}}));});const listener=e=>{const s=JSON.stringify(e);for(const c of wss.clients)if(c.readyState===1)c.send(s);};events.on('event',listener);server.on('close',()=>events.off('event',listener));return {server,wss};}
