import fs from 'node:fs'; import fsp from 'node:fs/promises'; import path from 'node:path'; import crypto from 'node:crypto';
import {config} from '../config.js'; import {db,now,setting,setSetting} from '../database/index.js'; import {emit} from '../events.js'; import {Events} from '../contracts.js';

export function allowedRoots(){return setting('storage_roots',config.storageRoots).map(x=>path.resolve(x));}
function real(p){try{return fs.realpathSync.native(p)}catch{return path.resolve(p)}}
export function safePath(input){if(typeof input!=='string'||input.includes('\0'))throw Object.assign(new Error('Invalid path'),{code:'PATH_FORBIDDEN'});const p=real(path.resolve(input));const ok=allowedRoots().map(real).some(root=>p===root||p.startsWith(root+path.sep));if(!ok)throw Object.assign(new Error('Path is outside configured storage roots'),{code:'PATH_FORBIDDEN'});return p;}
export async function browse(input){const p=safePath(input||allowedRoots().find(fs.existsSync)||allowedRoots()[0]);const entries=await fsp.readdir(p,{withFileTypes:true});const items=[];for(const e of entries){if(e.name.startsWith('.'))continue;try{const full=path.join(p,e.name),s=await fsp.stat(full);items.push({name:e.name,path:full,type:e.isDirectory()?'directory':'file',size:e.isFile()?s.size:null,mtimeMs:s.mtimeMs});}catch{}}items.sort((a,b)=>a.type===b.type?a.name.localeCompare(b.name):a.type==='directory'?-1:1);return {path:p,parent:allowedRoots().some(r=>r===p)?null:path.dirname(p),items};}
export function cheapFingerprint(p,size,mtimeMs){return crypto.createHash('sha256').update(`${p}\0${size}\0${Math.trunc(mtimeMs)}`).digest('hex');}
async function walk(root,onFile,signal){const stack=[root];while(stack.length){if(signal?.aborted)throw new Error('Scan cancelled');const dir=stack.pop();let es;try{es=await fsp.readdir(dir,{withFileTypes:true});}catch{continue;}for(const e of es){if(e.name.startsWith('.'))continue;const p=path.join(dir,e.name);try{if(e.isDirectory())stack.push(p);else if(e.isFile())await onFile(p,await fsp.stat(p));}catch{}}}}
let scanning=false;
export async function scan(input){if(scanning)throw Object.assign(new Error('A scan is already running'),{code:'CONFLICT'});scanning=true;const root=safePath(input);let scanAt=now();const previous=db().prepare(`SELECT MAX(last_seen_at) value FROM local_files WHERE canonical_path LIKE ?`).get(root+path.sep+'%')?.value;if(previous&&previous>=scanAt)scanAt=new Date(Date.parse(previous)+1).toISOString();let count=0,bytes=0;emit(Events.SCAN_STARTED,{root});try{await walk(root,async(p,s)=>{const fp=cheapFingerprint(p,s.size,s.mtimeMs);db().prepare(`INSERT INTO local_files(canonical_path,name,type,size,mtime_ms,fingerprint,last_seen_at,missing) VALUES(?,?,?,?,?,?,?,0) ON CONFLICT(canonical_path) DO UPDATE SET name=excluded.name,size=excluded.size,mtime_ms=excluded.mtime_ms,fingerprint=excluded.fingerprint,last_seen_at=excluded.last_seen_at,missing=0`).run(p,path.basename(p),'file',s.size,Math.trunc(s.mtimeMs),fp,scanAt);count++;bytes+=s.size;if(count%100===0)emit(Events.SCAN_PROGRESS,{root,files:count,bytes});});db().prepare(`UPDATE local_files SET missing=1 WHERE canonical_path LIKE ? AND last_seen_at<>?`).run(root+path.sep+'%',scanAt);const result={root,files:count,bytes,completedAt:now()};setSetting('last_scan',result);emit(Events.SCAN_COMPLETED,result);return result;}finally{scanning=false;}}
export async function expandSource(input){const root=safePath(input),s=await fsp.stat(root);const out=[];if(s.isFile())out.push({path:root,relativePath:path.basename(root),size:s.size,mtimeMs:Math.trunc(s.mtimeMs),fingerprint:cheapFingerprint(root,s.size,s.mtimeMs)});else await walk(root,async(p,st)=>out.push({path:p,relativePath:path.relative(root,p),size:st.size,mtimeMs:Math.trunc(st.mtimeMs),fingerprint:cheapFingerprint(p,st.size,st.mtimeMs)}));return out;}
export async function deviceStorage(){for(const root of allowedRoots()){try{const s=await fsp.statfs(root);const total=Number(s.blocks*s.bsize),available=Number(s.bavail*s.bsize);return {root,total,used:total-available,available,percentage:total?((total-available)/total*100):0};}catch{}}return {root:null,total:null,used:null,available:null,percentage:null,error:'Storage is not accessible. Run termux-setup-storage.'};}
