import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';import WebSocket from 'ws';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'termudrive-test-'));process.env.TERMUDRIVE_DB=path.join(tmp,'termudrive.db');process.env.TERMUDRIVE_STORAGE_ROOTS=tmp;process.env.TERMUDRIVE_PORT='18765';process.env.TERMUDRIVE_HOST='127.0.0.1';
const database=await import('../src/database/index.js'),{db,openDatabase,closeDatabase,now}=database;const {scan,expandSource,cheapFingerprint,safePath}=await import('../src/filesystem/index.js');const {claimNext,recoverClaims}=await import('../src/core/queue.js');const {assertTransition}=await import('../src/contracts.js');
const {classifyFailure,retryDelay}=await import('../src/core/workers.js');

test('migration creates complete durable schema',()=>{openDatabase();const names=db().prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(x=>x.name);for(const n of ['accounts','local_files','remote_files','file_mappings','jobs','job_files','upload_sessions','notifications','metrics'])assert.ok(names.includes(n),n);assert.equal(db().prepare('PRAGMA integrity_check').get().integrity_check,'ok')});

test('filesystem safety, recursive expansion and incremental scan',async()=>{const dir=path.join(tmp,'device'),sub=path.join(dir,'nested');fs.mkdirSync(sub,{recursive:true});fs.writeFileSync(path.join(dir,'a.txt'),'alpha');fs.writeFileSync(path.join(sub,'b.txt'),'beta');assert.equal(safePath(dir),dir);assert.throws(()=>safePath('/etc/passwd'));const escapeLink=path.join(dir,'escape');fs.symlinkSync('/etc',escapeLink);assert.throws(()=>safePath(escapeLink));fs.unlinkSync(escapeLink);const expanded=await expandSource(dir);assert.equal(expanded.length,2);const first=await scan(dir),second=await scan(dir);assert.equal(first.files,2);assert.equal(second.files,2);assert.equal(db().prepare('SELECT COUNT(*) n FROM local_files').get().n,2);fs.unlinkSync(path.join(dir,'a.txt'));await scan(dir);assert.equal(db().prepare('SELECT missing FROM local_files WHERE name=?').get('a.txt').missing,1)});

test('state machine rejects inconsistent transitions',()=>{assert.doesNotThrow(()=>assertTransition('QUEUED','PREPARING'));assert.throws(()=>assertTransition('UPLOADED','UPLOADING'),/Invalid transition/)});

test('retry engine classifies rate, auth, storage, network and permanent failures',()=>{assert.equal(classifyFailure(Object.assign(new Error('rate'),{status:429})),'RATE_LIMIT');assert.equal(classifyFailure(Object.assign(new Error('auth'),{status:401})),'AUTH');assert.equal(classifyFailure(Object.assign(new Error('storage quota'),{status:403})),'STORAGE_FULL');assert.equal(classifyFailure(new Error('network fetch failed')),'NETWORK');assert.equal(classifyFailure(Object.assign(new Error('bad request'),{status:400})),'PERMANENT');assert.equal(retryDelay(2,'7'),7000);const d=retryDelay(3);assert.ok(d>=6000&&d<=10000)});

test('transactional claim prevents duplicate worker ownership',()=>{const t=now(),a=db().prepare(`INSERT INTO accounts(provider,provider_account_id,email,status,created_at,updated_at) VALUES('fake','acct','x@test','CONNECTED',?,?)`).run(t,t).lastInsertRowid;db().prepare(`INSERT INTO jobs(id,account_id,source_path,destination_id,state,duplicate_policy,worker_count,total_files,total_bytes,created_at,updated_at) VALUES('j1',?,?,'root','QUEUED','SKIP_EXISTING',3,1,5,?,?)`).run(a,tmp,t,t);db().prepare(`INSERT INTO job_files(id,job_id,source_path,relative_path,state,size,mtime_ms,fingerprint,created_at,updated_at) VALUES('f1','j1',?,'a','QUEUED',5,0,'fp',?,?)`).run(path.join(tmp,'a'),t,t);const one=claimNext(),two=claimNext();assert.equal(one.id,'f1');assert.ok(one.claim_token);assert.equal(two,null)});

test('startup recovery persists resumable offset and clears abandoned claim',()=>{db().prepare(`INSERT INTO upload_sessions(job_file_id,provider,session_uri,uploaded_bytes,total_bytes,last_activity,state) VALUES('f1','fake','session://safe',3,5,?,'ACTIVE')`).run(now());const n=recoverClaims();assert.equal(n,1);const f=db().prepare('SELECT state,claim_token FROM job_files WHERE id=?').get('f1');assert.equal(f.state,'RETRY_WAIT');assert.equal(f.claim_token,null);assert.equal(db().prepare('SELECT uploaded_bytes FROM upload_sessions WHERE job_file_id=?').get('f1').uploaded_bytes,3)});

test('large queue claims every row exactly once',()=>{const t=now();db().prepare(`UPDATE job_files SET state='CANCELLED' WHERE id='f1'`).run();db().exec('BEGIN');try{const ins=db().prepare(`INSERT INTO job_files(id,job_id,source_path,relative_path,state,size,mtime_ms,fingerprint,created_at,updated_at) VALUES(?, 'j1', ?, ?, 'QUEUED',1,0,'x',?,?)`);for(let i=0;i<1000;i++)ins.run(`bulk-${i}`,path.join(tmp,`bulk-${i}`),`bulk-${i}`,t,t);db().exec('COMMIT')}catch(e){db().exec('ROLLBACK');throw e}const ids=new Set();for(let i=0;i<1000;i++){const x=claimNext();assert.ok(x);assert.ok(!ids.has(x.id));ids.add(x.id)}assert.equal(ids.size,1000);assert.equal(claimNext(),null)});

test('backend rejects hostile Origin, survives browser disconnect and shuts down',async()=>{closeDatabase();const child=spawn(process.execPath,['src/app.js'],{cwd:path.resolve(''),env:{...process.env,TERMUDRIVE_FOREGROUND:'0'},stdio:'ignore'});try{let ready=false;for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,100));try{const r=await fetch('http://127.0.0.1:18765/api/v1/system/snapshot');if(r.ok){ready=true;break}}catch{}}assert.equal(ready,true);const page=await fetch('http://127.0.0.1:18765/');assert.equal(page.status,200);assert.match(await page.text(),/TermuDrive/);assert.equal((await fetch('http://127.0.0.1:18765/api/v1/system/health',{headers:{origin:'https://evil.example'}})).status,403);const ws=new WebSocket('ws://127.0.0.1:18765/ws');await once(ws,'open');ws.close();await once(ws,'close');assert.equal((await fetch('http://127.0.0.1:18765/api/v1/system/health')).status,200);}finally{if(child.exitCode===null){child.kill('SIGTERM');await once(child,'exit');}}assert.equal(child.exitCode,0)});

test.after(()=>{try{closeDatabase()}catch{}fs.rmSync(tmp,{recursive:true,force:true})});
