#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),pidPath=path.join(root,'runtime','termudrive.pid'),logPath=path.join(root,'logs','termudrive.log'),base=`http://${process.env.TERMUDRIVE_HOST||'127.0.0.1'}:${process.env.TERMUDRIVE_PORT||8765}/api/v1`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));function pid(){try{return Number(fs.readFileSync(pidPath,'utf8').trim())}catch{return null}}function alive(p){if(!p)return false;try{process.kill(p,0);return true}catch{return false}}
async function request(endpoint,options={}){const r=await fetch(base+endpoint,{headers:{'content-type':'application/json',...options.headers},...options});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error?.message||`HTTP ${r.status}`);return x.data}
function print(x){if(typeof x==='string')console.log(x);else console.log(JSON.stringify(x,null,2))}
async function start(){const p=pid();if(alive(p))return console.log(`TermuDrive is already running (PID ${p}).`);if(p)try{fs.unlinkSync(pidPath)}catch{}fs.mkdirSync(path.dirname(logPath),{recursive:true});const fd=fs.openSync(logPath,'a');const child=spawn(process.execPath,[path.join(root,'src','app.js')],{cwd:root,detached:true,stdio:['ignore',fd,fd],env:{...process.env,TERMUDRIVE_FOREGROUND:'0'}});child.unref();for(let i=0;i<30;i++){await sleep(250);if(alive(child.pid)){try{await request('/system/health');return console.log(`TermuDrive started (PID ${child.pid}) at ${base.replace('/api/v1','')}`)}catch{}}}throw new Error(`TermuDrive failed to start. Check ${logPath}`)}
async function stop(){const p=pid();if(!alive(p)){if(p)try{fs.unlinkSync(pidPath)}catch{}return console.log('TermuDrive is not running.')}process.kill(p,'SIGTERM');for(let i=0;i<50&&alive(p);i++)await sleep(200);if(alive(p))throw new Error('Graceful shutdown timed out; inspect logs before taking further action.');console.log('TermuDrive stopped cleanly.')}
async function status(){const p=pid();if(!alive(p))return print({running:false,stalePid:!!p,pid:p});try{print({running:true,pid:p,address:base.replace('/api/v1',''),health:await request('/system/health')})}catch(e){print({running:true,pid:p,api:false,error:e.message})}}
async function doctor(){try{const d=alive(pid())?await request('/system/doctor'):(await import('../src/core/system.js')).doctor&&await (await import('../src/core/system.js')).doctor();for(const x of d.checks)console.log(`${x.status.padEnd(7)} ${x.name.padEnd(18)} ${x.message}`);process.exitCode=d.ok?0:1;}catch(e){console.error('ERROR   Doctor failed:',e.message);process.exitCode=1}}
async function logs(){if(!fs.existsSync(logPath))return console.log('No log file yet.');const lines=fs.readFileSync(logPath,'utf8').trim().split('\n').slice(-100);console.log(lines.join('\n'))}
async function upload(p){if(!p)throw new Error('Usage: termudrive upload <path> [destination-id]');const full=path.resolve(p),destinationId=process.argv[4]||'root';const pf=await request('/jobs/preflight',{method:'POST',body:JSON.stringify({sourcePath:full,destinationId,duplicatePolicy:'SKIP_EXISTING'})});print(pf);if(pf.status==='BLOCKED')throw new Error('Preflight blocked this upload.');const j=await request('/jobs',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({sourcePath:full,destinationId,duplicatePolicy:'SKIP_EXISTING'})});print(j)}
async function configCmd(){print(await request('/settings'))}async function account(){print(await request('/accounts'))}
const cmd=process.argv[2]||'help';try{if(cmd==='start')await start();else if(cmd==='stop')await stop();else if(cmd==='restart'){await stop();await start()}else if(cmd==='status')await status();else if(cmd==='doctor')await doctor();else if(cmd==='logs')await logs();else if(cmd==='upload')await upload(process.argv[3]);else if(cmd==='queue')print(await request('/jobs?limit=100'));else if(cmd==='pause')print(await request('/queue/pause',{method:'POST'}));else if(cmd==='resume')print(await request('/queue/resume',{method:'POST'}));else if(cmd==='retry')print(await request('/queue/retry-failed',{method:'POST'}));else if(cmd==='account')await account();else if(cmd==='config')await configCmd();else console.log(`TermuDrive CLI\n\n  start | stop | restart | status | doctor | logs\n  upload <path> [destination-id]\n  queue | pause | resume | retry | account | config`);}catch(e){console.error(`ERROR: ${e.message}`);process.exitCode=1}
