import fs from 'node:fs';import path from 'node:path';
import {db,transaction,now,setting} from '../database/index.js';import {claimNext,queueSummary} from './queue.js';import {GoogleDriveProvider} from '../providers/google-drive/index.js';import {cheapFingerprint} from '../filesystem/index.js';import {config} from '../config.js';import {emit} from '../events.js';import {Events,FileState,Severity} from '../contracts.js';import {notify,history} from './notifications.js';import {addBytes,metric,liveMetrics} from './metrics.js';import {isOnline} from './network.js';import {log} from '../logger.js';

let running=false,accepting=true,timers=[],active=0;const folderLocks=new Map();
export function classifyFailure(e){if(e.code==='AUTH_REQUIRED'||e.status===401)return 'AUTH';if(e.status===403&&/storage|quota/i.test(e.message))return 'STORAGE_FULL';if(e.status===429)return 'RATE_LIMIT';if(e.status>=500||e.status===408)return 'TRANSIENT_API';if(/fetch|network|ENET|ECONN|timeout/i.test(e.message))return 'NETWORK';if(e.code?.startsWith('E'))return 'SOURCE_ERROR';return e.status>=400&&e.status<500?'PERMANENT':'TRANSIENT_API';}
export function retryDelay(retry,retryAfter){if(retryAfter&&!Number.isNaN(Number(retryAfter)))return Number(retryAfter)*1000;return Math.min(15*60_000,1000*2**Math.min(retry,10))*(0.75+Math.random()*0.5);}
async function ensureFolder(provider,base,relativePath){const dirs=path.dirname(relativePath).split(path.sep).filter(x=>x&&x!=='.');let parent=base;for(const name of dirs){const key=`${provider.accountId}:${parent}:${name}`;let promise=folderLocks.get(key);if(!promise){promise=(async()=>{const r=await provider.listFiles({parentId:parent,query:name,pageSize:100});const found=r.files.find(x=>x.name===name&&x.mimeType==='application/vnd.google-apps.folder');return found?.id||(await provider.createFolder(name,parent)).id;})();folderLocks.set(key,promise);promise.finally(()=>folderLocks.delete(key));}parent=await promise;}return parent;}
function ownedUpdate(file,sql,...args){const r=db().prepare(sql).run(...args,file.id,file.claim_token);if(!r.changes)throw Object.assign(new Error('Queue claim no longer owned'),{code:'CLAIM_LOST'});}
async function processFile(file){const job=db().prepare('SELECT * FROM jobs WHERE id=?').get(file.job_id),provider=new GoogleDriveProvider(job.account_id);let stat;try{stat=await fs.promises.stat(file.source_path);}catch{ownedUpdate(file,`UPDATE job_files SET state='SOURCE_MISSING',error_class='SOURCE_ERROR',error_message='Source no longer exists',claim_token=NULL,updated_at=? WHERE id=? AND claim_token=?`,now());notify('SOURCE_MISSING','Source file missing',file.source_path,Severity.ERROR,'job',job.id);return finalizeJob(job.id);}
  const fp=cheapFingerprint(file.source_path,stat.size,stat.mtimeMs);if(stat.size!==file.size||Math.trunc(stat.mtimeMs)!==file.mtime_ms||fp!==file.fingerprint){ownedUpdate(file,`UPDATE job_files SET state='SOURCE_CHANGED',error_class='SOURCE_ERROR',error_message='Source changed after manifest creation',claim_token=NULL,updated_at=? WHERE id=? AND claim_token=?`,now());notify('SOURCE_CHANGED','Source file changed',file.source_path,Severity.WARNING,'job',job.id);return finalizeJob(job.id);}
  if(!isOnline())throw Object.assign(new Error('Network is offline'),{code:'NETWORK'});
  const parent=await ensureFolder(provider,job.destination_id,file.relative_path);let session=db().prepare('SELECT * FROM upload_sessions WHERE job_file_id=?').get(file.id),uri=session?.session_uri,offset=session?.uploaded_bytes||0;
  if(uri){const probe=await provider.sessionOffset(uri,file.size);if(probe.complete)return verifyAndComplete(file,job,provider,probe.file);if(probe.expired){uri=null;offset=0;}else offset=probe.offset;}
  let existingId=null;if(job.duplicate_policy==='REPLACE_OR_REMAP'){const m=db().prepare(`SELECT r.drive_file_id FROM file_mappings m JOIN remote_files r ON r.id=m.remote_file_id WHERE m.local_file_id=? AND m.account_id=?`).get(file.local_file_id,job.account_id);existingId=m?.drive_file_id||null;}
  if(!uri){uri=await provider.beginUpload(file,parent,existingId);db().prepare(`INSERT INTO upload_sessions(job_file_id,provider,session_uri,uploaded_bytes,total_bytes,last_activity,state) VALUES(?,'google',?,?,?,?,'ACTIVE') ON CONFLICT(job_file_id) DO UPDATE SET session_uri=excluded.session_uri,uploaded_bytes=0,last_activity=excluded.last_activity,state='ACTIVE'`).run(file.id,uri,0,file.size,now());offset=0;}
  ownedUpdate(file,`UPDATE job_files SET state='UPLOADING',uploaded_bytes=?,updated_at=? WHERE id=? AND claim_token=?`,offset,now());
  while(offset<file.size){const current=db().prepare('SELECT jf.state,j.state job_state FROM job_files jf JOIN jobs j ON j.id=jf.job_id WHERE jf.id=?').get(file.id);if(current.job_state==='PAUSED'||current.state==='PAUSED')throw Object.assign(new Error('Paused'),{code:'PAUSED'});if(current.job_state==='CANCELLED')throw Object.assign(new Error('Cancelled'),{code:'CANCELLED'});if(!running||!accepting)throw Object.assign(new Error('Shutdown'),{code:'SHUTDOWN'});const result=await provider.uploadChunk(uri,file,offset,setting('chunk_size',config.chunkSize)),delta=result.offset-offset;offset=result.offset;transaction(d=>{d.prepare('UPDATE upload_sessions SET uploaded_bytes=?,last_activity=?,state=? WHERE job_file_id=?').run(offset,now(),result.complete?'COMPLETE':'ACTIVE',file.id);d.prepare(`UPDATE job_files SET uploaded_bytes=?,state=?,updated_at=? WHERE id=? AND claim_token=?`).run(offset,result.complete?'VERIFYING':'UPLOADING',now(),file.id,file.claim_token);});addBytes(delta);emit(Events.FILE_PROGRESS,{jobId:job.id,fileId:file.id,uploadedBytes:offset,totalBytes:file.size});if(result.complete)return verifyAndComplete(file,job,provider,result.file);}
}
async function verifyAndComplete(file,job,provider,remote){const verified=await provider.verify(remote.id);if(verified.trashed||Number(verified.size)!==Number(file.size))throw Object.assign(new Error('Remote verification size/state mismatch'),{code:'REMOTE_VERIFY_FAILED'});return complete(file,job,verified);}
function complete(file,job,remote){transaction(d=>{const t=now();const r=d.prepare(`INSERT INTO remote_files(account_id,drive_file_id,name,size,md5_checksum,mime_type,parent_id,trashed,modified_time,last_seen_at,metadata_json) VALUES(?,?,?,?,?,?,?,0,?,?,?) ON CONFLICT(account_id,drive_file_id) DO UPDATE SET name=excluded.name,size=excluded.size,md5_checksum=excluded.md5_checksum,parent_id=excluded.parent_id,last_seen_at=excluded.last_seen_at,metadata_json=excluded.metadata_json RETURNING id`).get(job.account_id,remote.id,remote.name||path.basename(file.source_path),Number(remote.size)||file.size,remote.md5Checksum||null,remote.mimeType||'application/octet-stream',remote.parents?.[0]||job.destination_id,remote.modifiedTime||null,t,JSON.stringify(remote));d.prepare(`INSERT INTO file_mappings(local_file_id,account_id,remote_file_id,uploaded_size,uploaded_mtime_ms,uploaded_fingerprint,uploaded_at,last_verified_at,verification_status) VALUES(?,?,?,?,?,?,?,?, 'VERIFIED') ON CONFLICT(local_file_id,account_id) DO UPDATE SET remote_file_id=excluded.remote_file_id,uploaded_size=excluded.uploaded_size,uploaded_mtime_ms=excluded.uploaded_mtime_ms,uploaded_fingerprint=excluded.uploaded_fingerprint,uploaded_at=excluded.uploaded_at,last_verified_at=excluded.last_verified_at,verification_status='VERIFIED'`).run(file.local_file_id,job.account_id,r.id,file.size,file.mtime_ms,file.fingerprint,t,t);d.prepare(`UPDATE job_files SET state='UPLOADED',remote_file_id=?,uploaded_bytes=size,claim_token=NULL,claimed_at=NULL,error_class=NULL,error_message=NULL,updated_at=? WHERE id=? AND claim_token=?`).run(remote.id,t,file.id,file.claim_token);d.prepare('DELETE FROM upload_sessions WHERE job_file_id=?').run(file.id);});metric('files_completed',liveMetrics().files_completed+1);history('FILE_COMPLETED',file.id,'File uploaded',{jobId:job.id,path:file.source_path});emit(Events.FILE_COMPLETED,{jobId:job.id,fileId:file.id});finalizeJob(job.id);}
function fail(file,e){if(e.code==='CLAIM_LOST')return;const cls=classifyFailure(e),retry=file.retry_count+1,max=setting('max_retries',config.maxRetries),t=now();let state='FAILED',next=null;if(e.code==='PAUSED')state='PAUSED';else if(e.code==='CANCELLED')state='CANCELLED';else if(e.code==='SHUTDOWN'){state=file.uploaded_bytes?'RETRY_WAIT':'QUEUED';next=t;}else if(cls==='NETWORK'){state='WAITING_NETWORK';next=new Date(Date.now()+15000).toISOString();}else if(!['AUTH','STORAGE_FULL','PERMANENT','SOURCE_ERROR'].includes(cls)&&retry<=max){state='RETRY_WAIT';next=new Date(Date.now()+retryDelay(retry,e.retryAfter)).toISOString();}db().prepare(`UPDATE job_files SET state=?,retry_count=?,next_attempt_at=?,error_class=?,error_message=?,claim_token=NULL,claimed_at=NULL,updated_at=? WHERE id=? AND claim_token=?`).run(state,retry,next,cls,String(e.message).slice(0,500),t,file.id,file.claim_token);if(state==='FAILED'){metric('files_failed',liveMetrics().files_failed+1);notify('UPLOAD_FAILED','Upload failed',`${path.basename(file.source_path)}: ${e.message}`,Severity.ERROR,'job',file.job_id);emit(Events.FILE_FAILED,{jobId:file.job_id,fileId:file.id,errorClass:cls,message:e.message});}else if(state==='RETRY_WAIT')metric('retry_count',liveMetrics().retry_count+1);log(state==='FAILED'?'ERROR':'WARN','worker upload interrupted',{jobId:file.job_id,fileId:file.id,class:cls,state,message:e.message});finalizeJob(file.job_id);}
function finalizeJob(jobId){transaction(d=>{const s=d.prepare(`SELECT COUNT(*) total,SUM(state='UPLOADED') done,SUM(state='FAILED') failed,SUM(state IN ('SOURCE_CHANGED','SOURCE_MISSING','MISSING_REMOTE')) attention,SUM(CASE WHEN state='UPLOADED' THEN size ELSE 0 END) bytes,SUM(state IN ('QUEUED','PREPARING','UPLOADING','VERIFYING','WAITING_NETWORK','RETRY_WAIT','PAUSED')) active FROM job_files WHERE job_id=?`).get(jobId);let state=s.active?'RUNNING':s.done===s.total?'COMPLETED':s.failed||s.attention?'PARTIALLY_FAILED':'FAILED';const old=d.prepare('SELECT state FROM jobs WHERE id=?').get(jobId);d.prepare(`UPDATE jobs SET state=?,completed_files=?,completed_bytes=?,failed_files=?,completed_at=CASE WHEN ? IN ('COMPLETED','PARTIALLY_FAILED','FAILED') THEN ? ELSE completed_at END,updated_at=? WHERE id=? AND state<>'CANCELLED'`).run(state,s.done||0,s.bytes||0,(s.failed||0)+(s.attention||0),state,now(),now(),jobId);if(old&&old.state!==state&&['COMPLETED','PARTIALLY_FAILED'].includes(state)){const type=state==='COMPLETED'?'JOB_COMPLETED':'JOB_PARTIALLY_FAILED';notify(type,state==='COMPLETED'?'Upload complete':'Upload needs attention',`${s.done}/${s.total} file(s) completed.`,state==='COMPLETED'?Severity.SUCCESS:Severity.WARNING,'job',jobId);emit(Events.JOB_COMPLETED,{id:jobId,state});}});emit(Events.QUEUE_UPDATED,{summary:queueSummary()});}
async function loop(index){while(running){if(!accepting){await new Promise(r=>setTimeout(r,200));continue;}const file=claimNext();if(!file){await new Promise(r=>setTimeout(r,500));continue;}active++;metric('active_workers',active);try{await processFile(file);}catch(e){fail(file,e);}finally{active--;metric('active_workers',active);}}}
export function startWorkers(){if(running)return;running=true;accepting=true;const count=setting('worker_count',config.workers);for(let i=0;i<count;i++)timers.push(loop(i));log('INFO','worker pool started',{count});}
export async function stopWorkers(){accepting=false;const until=Date.now()+10000;while(active&&Date.now()<until)await new Promise(r=>setTimeout(r,100));running=false;await Promise.allSettled(timers);timers=[];log('INFO','worker pool stopped',{active});}
export function pauseClaims(){accepting=false;}export function resumeClaims(){accepting=true;}export function workerStatus(){return {running,accepting,active,configured:setting('worker_count',config.workers)};}
