import fs from 'node:fs'; import path from 'node:path';
import {CloudProvider} from '../provider.interface.js'; import {db,now} from '../../database/index.js'; import {encrypt,decrypt} from '../../security/secrets.js'; import {config} from '../../config.js';import {notify} from '../../core/notifications.js';import {Severity} from '../../contracts.js';
const AUTH='https://accounts.google.com/o/oauth2/v2/auth',TOKEN='https://oauth2.googleapis.com/token',DRIVE='https://www.googleapis.com/drive/v3';
const SCOPE='https://www.googleapis.com/auth/drive';
function cred(){const r=db().prepare('SELECT * FROM oauth_credentials WHERE provider=?').get('google');if(!r)throw Object.assign(new Error('Google OAuth credentials are not configured'),{code:'AUTH_REQUIRED'});return {...r,client_secret:decrypt(r.client_secret_enc)};}
function tokenRow(accountId){return db().prepare('SELECT * FROM account_tokens WHERE account_id=?').get(accountId);}
export class GoogleDriveProvider extends CloudProvider{
  constructor(accountId=null){super();this.accountId=accountId;}
  saveCredentials({clientId,clientSecret}){if(!clientId||!clientSecret)throw new Error('Client ID and Client Secret are required');const t=now(),redirectUri=`http://${config.host}:${config.port}/api/v1/accounts/google/callback`;db().prepare(`INSERT INTO oauth_credentials(provider,client_id,client_secret_enc,redirect_uri,created_at,updated_at) VALUES('google',?,?,?,?,?) ON CONFLICT(provider) DO UPDATE SET client_id=excluded.client_id,client_secret_enc=excluded.client_secret_enc,redirect_uri=excluded.redirect_uri,updated_at=excluded.updated_at`).run(clientId,encrypt(clientSecret),redirectUri,t,t);return {clientId,redirectUri};}
  authUrl(state){const c=cred(),u=new URL(AUTH);Object.entries({client_id:c.client_id,redirect_uri:c.redirect_uri,response_type:'code',scope:SCOPE,access_type:'offline',prompt:'consent',state}).forEach(([k,v])=>u.searchParams.set(k,v));return u.toString();}
  async exchange(code){const c=cred(),body=new URLSearchParams({code,client_id:c.client_id,client_secret:c.client_secret,redirect_uri:c.redirect_uri,grant_type:'authorization_code'});const r=await fetch(TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const tok=await r.json();if(!r.ok)throw new Error(tok.error_description||'OAuth exchange failed');const about=await fetch(`${DRIVE}/about?fields=user,storageQuota`,{headers:{authorization:`Bearer ${tok.access_token}`}});const data=await about.json();if(!about.ok)throw new Error(data.error?.message||'Drive verification failed');const t=now();let account=db().prepare(`SELECT * FROM accounts WHERE provider='google' AND provider_account_id=?`).get(data.user.permissionId);if(!account){const x=db().prepare(`INSERT INTO accounts(provider,provider_account_id,email,display_name,status,created_at,updated_at) VALUES('google',?,?,?,?,?,?)`).run(data.user.permissionId,data.user.emailAddress,data.user.displayName,'CONNECTED',t,t);account={id:Number(x.lastInsertRowid)};}else db().prepare(`UPDATE accounts SET email=?,display_name=?,status='CONNECTED',updated_at=? WHERE id=?`).run(data.user.emailAddress,data.user.displayName,t,account.id);const saved={access_token:tok.access_token,refresh_token:tok.refresh_token||this.readToken(account.id)?.refresh_token,expires_at:Date.now()+(tok.expires_in||3600)*1000};db().prepare(`INSERT INTO account_tokens(account_id,token_enc,expires_at,scope,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(account_id) DO UPDATE SET token_enc=excluded.token_enc,expires_at=excluded.expires_at,scope=excluded.scope,updated_at=excluded.updated_at`).run(account.id,encrypt(JSON.stringify(saved)),new Date(saved.expires_at).toISOString(),tok.scope||SCOPE,t);this.accountId=account.id;return {id:account.id,email:data.user.emailAddress,name:data.user.displayName,quota:data.storageQuota};}
  readToken(id=this.accountId){const r=tokenRow(id);return r?JSON.parse(decrypt(r.token_enc)):null;}
  async accessToken(){let t=this.readToken();if(!t)throw Object.assign(new Error('Google account is not connected'),{code:'AUTH_REQUIRED'});if(t.expires_at>Date.now()+60000)return t.access_token;const c=cred();if(!t.refresh_token)throw Object.assign(new Error('Google authorization expired; reconnect the account'),{code:'AUTH_REQUIRED'});const r=await fetch(TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.client_id,client_secret:c.client_secret,refresh_token:t.refresh_token,grant_type:'refresh_token'})});const n=await r.json();if(!r.ok){db().prepare(`UPDATE accounts SET status='AUTH_EXPIRED',updated_at=? WHERE id=?`).run(now(),this.accountId);notify('ACCOUNT_AUTH_EXPIRED','Google authorization expired','Reconnect the Google account to resume uploads.',Severity.ERROR,'account',String(this.accountId));throw Object.assign(new Error(n.error_description||'Token refresh failed'),{code:'AUTH_REQUIRED'});}t={...t,access_token:n.access_token,expires_at:Date.now()+(n.expires_in||3600)*1000};db().prepare('UPDATE account_tokens SET token_enc=?,expires_at=?,updated_at=? WHERE account_id=?').run(encrypt(JSON.stringify(t)),new Date(t.expires_at).toISOString(),now(),this.accountId);return t.access_token;}
  async request(url,options={}){const token=await this.accessToken();const r=await fetch(url,{...options,headers:{...options.headers,authorization:`Bearer ${token}`}});if(r.status===401)throw Object.assign(new Error('Google authorization expired'),{code:'AUTH_REQUIRED',status:401});if(!r.ok){let e={};try{e=await r.json()}catch{}const err=Object.assign(new Error(e.error?.message||`Google API ${r.status}`),{status:r.status,retryAfter:r.headers.get('retry-after')});throw err;}return r;}
  async getAccount(){return db().prepare(`SELECT id,email,display_name name,status FROM accounts WHERE id=?`).get(this.accountId);}
  async getQuota(){const r=await this.request(`${DRIVE}/about?fields=storageQuota,user`),x=await r.json(),q=x.storageQuota||{};return {limit:Number(q.limit)||null,usage:Number(q.usage)||0,usageInDrive:Number(q.usageInDrive)||0,available:q.limit?Number(q.limit)-Number(q.usage):null,user:x.user};}
  async listFiles({parentId='root',query='',pageToken='',pageSize=100}={}){const u=new URL(`${DRIVE}/files`),parts=[`'${String(parentId).replaceAll("'","\\'")}' in parents`,'trashed=false'];if(query)parts.push(`name contains '${String(query).replaceAll("'","\\'")}'`);u.searchParams.set('q',parts.join(' and '));u.searchParams.set('fields','nextPageToken,files(id,name,mimeType,size,modifiedTime,md5Checksum,parents,trashed)');u.searchParams.set('pageSize',String(Math.min(pageSize,200)));if(pageToken)u.searchParams.set('pageToken',pageToken);return (await this.request(u)).json();}
  async createFolder(name,parentId='root'){const r=await this.request(`${DRIVE}/files?fields=id,name,parents`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:[parentId]})});return r.json();}
  async beginUpload(file,parentId,existingId=null){const token=await this.accessToken(),meta={name:path.basename(file.path),parents:existingId?undefined:[parentId]};const url=existingId?`https://www.googleapis.com/upload/drive/v3/files/${existingId}?uploadType=resumable&fields=id,name,size,md5Checksum,parents`:`https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id,name,size,md5Checksum,parents`;const r=await fetch(url,{method:existingId?'PATCH':'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json; charset=UTF-8','x-upload-content-type':'application/octet-stream','x-upload-content-length':String(file.size)},body:JSON.stringify(meta)});if(!r.ok)throw Object.assign(new Error(`Cannot create resumable session (${r.status})`),{status:r.status});return r.headers.get('location');}
  async sessionOffset(uri,total){const token=await this.accessToken(),r=await fetch(uri,{method:'PUT',headers:{authorization:`Bearer ${token}`,'content-length':'0','content-range':`bytes */${total}`}});if(r.status===200||r.status===201)return {complete:true,file:await r.json()};if(r.status===308){const m=/bytes=0-(\d+)/.exec(r.headers.get('range')||'');return {complete:false,offset:m?Number(m[1])+1:0};}if(r.status===404||r.status===410)return {expired:true,offset:0};throw Object.assign(new Error(`Session probe failed (${r.status})`),{status:r.status});}
  async uploadChunk(uri,file,offset,size){const end=Math.min(file.size,offset+size)-1,len=end-offset+1,fh=await fs.promises.open(file.path,'r');try{const buf=Buffer.allocUnsafe(len),{bytesRead}=await fh.read(buf,0,len,offset);const token=await this.accessToken(),r=await fetch(uri,{method:'PUT',headers:{authorization:`Bearer ${token}`,'content-length':String(bytesRead),'content-range':`bytes ${offset}-${offset+bytesRead-1}/${file.size}`},body:buf.subarray(0,bytesRead)});if(r.status===200||r.status===201)return {complete:true,file:await r.json(),offset:file.size};if(r.status===308){const m=/bytes=0-(\d+)/.exec(r.headers.get('range')||'');return {complete:false,offset:m?Number(m[1])+1:offset+bytesRead};}let msg='';try{msg=(await r.json()).error?.message}catch{}throw Object.assign(new Error(msg||`Upload failed (${r.status})`),{status:r.status,retryAfter:r.headers.get('retry-after')});}finally{await fh.close();}}
  async verify(fileId){const r=await this.request(`${DRIVE}/files/${encodeURIComponent(fileId)}?fields=id,name,size,md5Checksum,parents,trashed`);return r.json();}
  disconnect(){db().prepare('DELETE FROM account_tokens WHERE account_id=?').run(this.accountId);db().prepare(`UPDATE accounts SET status='DISCONNECTED',updated_at=? WHERE id=?`).run(now(),this.accountId);}
}
export function connectedAccount(){return db().prepare(`SELECT id,email,display_name name,status FROM accounts WHERE status='CONNECTED' ORDER BY updated_at DESC LIMIT 1`).get();}
