export const FileState = Object.freeze({
  NOT_UPLOADED:'NOT_UPLOADED', QUEUED:'QUEUED', PREPARING:'PREPARING',
  UPLOADING:'UPLOADING', VERIFYING:'VERIFYING', UPLOADED:'UPLOADED',
  CHANGED:'CHANGED', WAITING_NETWORK:'WAITING_NETWORK', RETRY_WAIT:'RETRY_WAIT',
  FAILED:'FAILED', SOURCE_CHANGED:'SOURCE_CHANGED', SOURCE_MISSING:'SOURCE_MISSING',
  MISSING_REMOTE:'MISSING_REMOTE', PAUSED:'PAUSED', CANCELLED:'CANCELLED'
});
export const JobState = Object.freeze({QUEUED:'QUEUED',RUNNING:'RUNNING',PAUSED:'PAUSED',WAITING_NETWORK:'WAITING_NETWORK',COMPLETED:'COMPLETED',PARTIALLY_FAILED:'PARTIALLY_FAILED',FAILED:'FAILED',CANCELLED:'CANCELLED'});
export const Severity = Object.freeze({INFO:'INFO',SUCCESS:'SUCCESS',WARNING:'WARNING',ERROR:'ERROR'});
export const DuplicatePolicy = Object.freeze({SKIP_EXISTING:'SKIP_EXISTING',UPLOAD_ANYWAY:'UPLOAD_ANYWAY',REPLACE_OR_REMAP:'REPLACE_OR_REMAP'});
export const Events = Object.freeze({SYSTEM_STATUS:'system.status',NETWORK_CHANGED:'network.changed',SCAN_STARTED:'scan.started',SCAN_PROGRESS:'scan.progress',SCAN_COMPLETED:'scan.completed',JOB_CREATED:'job.created',JOB_UPDATED:'job.updated',JOB_COMPLETED:'job.completed',FILE_PROGRESS:'file.progress',FILE_COMPLETED:'file.completed',FILE_FAILED:'file.failed',QUEUE_UPDATED:'queue.updated',STORAGE_UPDATED:'storage.updated',NOTIFICATION_CREATED:'notification.created',METRICS_UPDATED:'metrics.updated',DRIVE_CONNECTED:'drive.connected',DRIVE_DISCONNECTED:'drive.disconnected'});

const allowed = {
  QUEUED:['PREPARING','PAUSED','CANCELLED','SOURCE_CHANGED','SOURCE_MISSING'],
  PREPARING:['UPLOADING','RETRY_WAIT','WAITING_NETWORK','FAILED','SOURCE_CHANGED','SOURCE_MISSING','PAUSED','CANCELLED'],
  UPLOADING:['VERIFYING','RETRY_WAIT','WAITING_NETWORK','FAILED','PAUSED','CANCELLED'],
  VERIFYING:['UPLOADED','RETRY_WAIT','FAILED','MISSING_REMOTE'],
  WAITING_NETWORK:['QUEUED','PREPARING','PAUSED','CANCELLED'],
  RETRY_WAIT:['QUEUED','PREPARING','PAUSED','CANCELLED','FAILED'],
  PAUSED:['QUEUED','CANCELLED'], FAILED:['QUEUED','CANCELLED'],
  SOURCE_CHANGED:['QUEUED','CANCELLED'], SOURCE_MISSING:['QUEUED','CANCELLED'],
  MISSING_REMOTE:['QUEUED','CANCELLED'], UPLOADED:[], CANCELLED:[]
};
export function assertTransition(from,to){ if(from===to)return; if(!allowed[from]?.includes(to)) throw Object.assign(new Error(`Invalid transition ${from} -> ${to}`),{code:'INVALID_STATE_TRANSITION'}); }

export const ErrorCode = Object.freeze({VALIDATION:'VALIDATION_ERROR',NOT_FOUND:'NOT_FOUND',CONFLICT:'CONFLICT',AUTH_REQUIRED:'AUTH_REQUIRED',PATH_FORBIDDEN:'PATH_FORBIDDEN',NETWORK:'NETWORK',STORAGE_FULL:'STORAGE_FULL',INTERNAL:'INTERNAL_ERROR'});

